### PR TITLE
Port to GTK 3

### PR DESCRIPTION
**Pull request by a-andre**
Signed-off-by: André Apitzsch <git@apitzsch.eu>

### CODE REVIEW

**Comment by krzk** [comment]
Looks good in general. I leave the merging into this branch to @mgreeraz.

**Comment by mgreeraz** [comment]
Hi @a-andre.  Your patch looks good and worked for me.  I need to pick up where I left off on the py3 port which your patch is based on.  I should be able to do this week.

**Comment by mgreeraz** [comment]
@a-andre, I rebased/reformatted your patch on top of my latest mag/python3-ize branch that is pushed.  I did some quick tests and it worked but please take a close look.  While you're at it, please add a more complete commit description including what your porting to GTK 3, why, and any other info that may be helpful to someone looking at it years from now.  Thx.

**Comment by krzk** [comment]
Merged as part of https://github.com/linux-nfc/neard/pull/25 . Closing. If something is missing/non-working, please open new pull request.

**Pull request closed without merging**
